### ISSUE TITLE
Vaadin 23.3 - ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/OrgChartAddon#60]
After upgrading to Vaadin 24.0.0.alpha7 we get the following error:
﻿
```
generated-flow-imports-7b1c6c38.js:22218 Uncaught (in promise) ReferenceError: jQuery is not defined
    at jquery.orgchart.js:17:13
    at jquery.orgchart.js:19:2
```

**Comment by paodb** [comment]
Same problem with Vaadin 23.3.2.
